name: "Schedule a release draft"
description: "Schedule a release draft every wednesday at 00:00 with version as date"
inputs:
  registry-name:
    description: "The name of the package registry"
    required: false
    type: string
    default: ghcr.io
  repository-name:
    description: "The name of the repository"
    required: false
    type: string
    default: altinn/altinn-auth-audit-log
  image-tag:
    description: "The image tag"
    required: true
    type: string
    default: cee42f683dfefdd92970de39e465a3121e74a96d
  
runs:
  using: "composite"
  steps:
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Get version number
      id: get_version_number
      shell: bash
      run: |
        deno run -A ./.github/actions/release/releaseversion.mts
        echo "RELEASE_VERSION=$(deno run -A ./.github/actions/release/releaseversion.mts)" >> $GITHUB_OUTPUT
    
    - name: print version
      shell: bash
      run: "echo Release version : '${{ steps.get_version_number.outputs.RELEASE_VERSION }}'" 

    - name: Add Version tag to Docker Image
      uses: shrink/actions-docker-registry-tag@v4
      with:
        registry: ${{ inputs.registry-name }}
        repository: '${{ inputs.repository-name }}'
        target: ${{ inputs.image-tag }}
        tags: ${{ steps.get_version_number.outputs.RELEASE_VERSION }}
