GRANT USAGE ON SCHEMA authz TO auth_auditlog;
GRANT SELECT,INSERT,UPDATE,REFERENCES,DELETE,TRUNCATE,TRIGGER ON ALL TABLES IN SCHEMA authz TO auth_auditlog;
GRANT ALL ON ALL SEQUENCES IN SCHEMA authz TO auth_auditlog;
