name: Build and publish to AT environments
on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  build-container-app:
    name: Build Container App
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup .NET
        uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: Log in to the Container registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          push: true
          tags: ghcr.io/altinn/altinn-auth-audit-log:${{ github.sha }}
          build-args: |
            SOURCE_REVISION_ID=${{ github.sha }}

  build-function-app:
    name: Build Function App
    runs-on: windows-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup .NET
        uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        shell: bash
        working-directory: ./src/Functions/Altinn.Auth.AuditLog.Functions
        run: dotnet restore

      - name: Build
        shell: bash
        working-directory: ./src/Functions/Altinn.Auth.AuditLog.Functions
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        shell: bash
        working-directory: ./src/Functions/Altinn.Auth.AuditLog.Functions
        run: dotnet publish --configuration Release --no-build --output ./output

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: function-app
          path: ./src/Functions/Altinn.Auth.AuditLog.Functions/output/
          include-hidden-files: true

  deploy-container-app:
    name: Deploy container-app to ${{ matrix.environment }}
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    needs:
      - build-container-app
      - build-function-app

    permissions:
      id-token: write
      contents: read
      packages: read

    strategy:
      fail-fast: false
      matrix:
        environment: [AT22, AT23, AT24]

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Download built function-app
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        with:
          name: function-app
          path: ./artifacts/function-app

      - name: Azure Login
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: ./.github/actions/deploy
        name: Deploy
        with:
          image-tag: ${{ github.sha }}
          resource-group: ${{ vars.CONTAINER_APP_RESOURCE_GROUP_NAME }}
          container-app: ${{ vars.CONTAINER_APP_NAME }}
          function-app: ${{ vars.AZURE_FUNCTIONAPP_NAME }}
          function-app-path: ./artifacts/function-app
