name: Schedule release
on:
  push:
    branches: [infrastructure/deploy-post-release]
  workflow_dispatch:

jobs:
  releaseversion:
    name: releaseversion
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: ./.github/actions/release
        with: 
          image_tag: ${{ github.sha}}
  
