name: Test

on:
  push:
    branches:
      - infra/testings

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  deploy-to-at21:
    name: Deploy to AT21
    runs-on: ubuntu-latest
    environment: AT21

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: ./.github/actions/deploy
        name: Deploy
        with:
          image-tag: ${{ github.sha }}
          resource-group: ${{ vars.CONTAINER_APP_RESOURCE_GROUP_NAME }}
          container-app: ${{ vars.CONTAINER_APP_NAME }}
          function-app: ${{ vars.AZURE_FUNCTIONAPP_NAME }}

  deploy-to-at22:
    name: Deploy to AT22
    runs-on: ubuntu-latest
    environment: AT22

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: ./.github/actions/deploy
        name: Deploy
        with:
          image-tag: ${{ github.sha }}
          resource-group: ${{ vars.CONTAINER_APP_RESOURCE_GROUP_NAME }}
          container-app: ${{ vars.CONTAINER_APP_NAME }}
          function-app: ${{ vars.AZURE_FUNCTIONAPP_NAME }}
