name: Test

on:
  push:
    branches:
      - infra/testings

jobs:
  deploy-to-tt02:
    runs-on: ubuntu-latest
    environment: AT21

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/deploy
        with:
          environment: AT21
          tag: ${{ github.sha }}
