name: Test

on:
  push:
    branches:
      - infra/testings

env:
  FA_DOTNET_VERSION: '8.0.x'

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  build-fa:
    name: Build function app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.FA_DOTNET_VERSION }}

      - name: Build function app
        shell: bash
        working-directory: ./src/Functions/Altinn.Auth.AuditLog.Functions
        run: dotnet build --configuration Release --output ./output

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: function-app
          path: ./src/Functions/Altinn.Auth.AuditLog.Functions/output

  deploy:
    name: Deploy to ${{ matrix.environment }}
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    needs:
      - build-fa

    strategy:
      matrix:
        # environment: [AT21, AT22, AT23, AT24]
        environment: [AT24]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download built function-app
        uses: actions/download-artifact@v4
        with:
          name: function-app
          path: ./artifacts/function-app

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: ./.github/actions/deploy
        name: Deploy
        with:
          # image-tag: ${{ github.sha }}
          image-tag: eab7f9ac319ae8de4158f67e40f659ba5e39a014
          resource-group: ${{ vars.CONTAINER_APP_RESOURCE_GROUP_NAME }}
          container-app: ${{ vars.CONTAINER_APP_NAME }}
          function-app: ${{ vars.AZURE_FUNCTIONAPP_NAME }}
          function-app-path: ./artifacts/function-app

  # deploy-to-prod:
  #   name: Deploy to AT22
  #   runs-on: ubuntu-latest
  #   environment: AT22

  #   needs:
  #     - deploy

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Azure Login
  #       uses: azure/login@v1
  #       with:
  #         client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  #     - uses: ./.github/actions/deploy
  #       name: Deploy
  #       with:
  #         image-tag: ${{ github.sha }}
  #         resource-group: ${{ vars.CONTAINER_APP_RESOURCE_GROUP_NAME }}
  #         container-app: ${{ vars.CONTAINER_APP_NAME }}
  #         function-app: ${{ vars.AZURE_FUNCTIONAPP_NAME }}
