name: Test

on:
  push:
    branches:
      - infra/testings

jobs:
  deploy-to-at21:
    name: Deploy to AT21
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: AT21
      image-tag: ${{ github.sha }}
