name: Test

on:
  push:
    branches:
      - infra/testings

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  deploy:
    name: Deploy to ${{ matrix.environment }}
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}

    strategy:
      matrix:
        # environment: [AT21, AT22, AT23, AT24]
        environment: [AT24]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: ./.github/actions/deploy
        name: Deploy
        with:
          # image-tag: ${{ github.sha }}
          image-tag: 7901558da421cb8e9f12a1c85d34ea627bb91a37
          resource-group: ${{ vars.CONTAINER_APP_RESOURCE_GROUP_NAME }}
          container-app: ${{ vars.CONTAINER_APP_NAME }}
          function-app: ${{ vars.AZURE_FUNCTIONAPP_NAME }}

  # deploy-to-prod:
  #   name: Deploy to AT22
  #   runs-on: ubuntu-latest
  #   environment: AT22

  #   needs:
  #     - deploy

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Azure Login
  #       uses: azure/login@v1
  #       with:
  #         client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  #     - uses: ./.github/actions/deploy
  #       name: Deploy
  #       with:
  #         image-tag: ${{ github.sha }}
  #         resource-group: ${{ vars.CONTAINER_APP_RESOURCE_GROUP_NAME }}
  #         container-app: ${{ vars.CONTAINER_APP_NAME }}
  #         function-app: ${{ vars.AZURE_FUNCTIONAPP_NAME }}
