name: Test

on:
  push:
    branches:
      - infra/testings

jobs:
  deploy-to-at21:
    name: Deploy to AT21
    runs-on: ubuntu-latest
    environment: AT21

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/deploy
        with:
          environment: AT21
          image-tag: ${{ github.sha }}
          resource-group: ${{ vars.CONTAINER_APP_RESOURCE_GROUP_NAME }}
          container-app: ${{ vars.CONTAINER_APP_NAME }}
          function-app: ${{ vars.AZURE_FUNCTIONAPP_NAME }}
